### ISSUE TITLE
3 Errors in Swift 3

### ISSUE THREAD

**Issue by NicholasBosak** [andrewcbancroft/SwiftRotateAnimation#1]
This no longer works in Swift 3
- Method does not override any method from its superclass
  override func animationDidStop(

-Type AnyObject to type CAAnimationDelegate
rotateAnimation.delegate = delegate

-Method does not override any method from it superclass
override func animationDid Stop

**Comment by andrewcbancroft** [comment]
I'm currently working through updating my repos and blog posts for Swift 3, so I'll do my best to take a look at this one soon.  Thanks for the heads-up!

**Comment by sungkim23** [comment]
Fix #2 - 

Remove the override.

In the refresh() func

self.timer = Timer(timeInterval: 5.0, repeats: true, block: {_ in
    self.shouldStopRotating = true
})

self.timer.fire()

The other methods were deprecated, however I don't know yet how to fix the delegate part :(

**Comment by andrewcbancroft** [comment]
Hey y'all!

Just wanted to let you know that I updated the project to Swift 3 with fixes to all three errors mentioned (after a _really_ long delay - my apologies!) Thanks a ton for spotting them and reporting them.
